### ISSUE TITLE
Removing collections is not working 

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#3340]
### Description of the issue

When I am trying to remove more than 20 collections then app is crashing

### Steps to reproduce the problem

1. Go to collections
2. Select collections which you want to remove
3. Click remove

### Expected Result
Collections are removed

### Actual Result
App is crashing

### Screenshots

[Untitled_ Mar 10, 2023 4_08 PM.webm](https://user-images.githubusercontent.com/25908728/224351734-672d1997-2606-4600-92d3-6a23dd7f92fd.webm)

### HTTP request and response from inspector

```

Provisional headers are shown
Learn more
Content-Type: text/plain;charset=UTF-8
Referer: https://master.staging.saleor.cloud/
sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36


```

### Console output

```
index.76dfc79e.js:115998 TypeError: listElements.find is not a function
    at isSelected2 (index.76dfc79e.js:133081:27)
    at CollectionList$2.jsxRuntime$2.exports.jsxs.children.jsxRuntime$2.exports.jsx.children.jsxRuntime$2.exports.jsx.children.jsxRuntime$2.exports.jsx.colSpan (index.76dfc79e.js:162182:46)
    at Array.map (<anonymous>)
    at renderCollection (index.76dfc79e.js:82461:21)
    at CollectionList$2 (index.76dfc79e.js:162178:19)
    at Ch$1 (index.76dfc79e.js:31939:8)
    at li$2 (index.76dfc79e.js:32411:8)
    at ck$1 (index.76dfc79e.js:34528:98)
    at bk$1 (index.76dfc79e.js:34007:12)
    at ak$1 (index.76dfc79e.js:34000:5)
    at Tj$1 (index.76dfc79e.js:33983:7)
    at Lj$1 (index.76dfc79e.js:33751:28)
    at index.76dfc79e.js:31185:18
    at exports.unstable_runWithPriority (index.76dfc79e.js:28873:14)
    at gg$2 (index.76dfc79e.js:31161:10)
    at jg$1 (index.76dfc79e.js:31181:7)
    at ig$1 (index.76dfc79e.js:31173:3)
    at Hb$1 (index.76dfc79e.js:35001:37)
    at gd$1 (index.76dfc79e.js:30178:5)
    at HTMLDivElement.sentryWrapped (index.76dfc79e.js:119171:18)```

### System information

Dashboard version:

`v?.?.?` (e.g. `v3.6.0`)

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [x ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ x] Chrome
- [ ] Edge
- [ ] Other

**Comment by wojteknowacki** [comment]
Working on the newest version so I am closing issue
